
Vagrant.configure("2") do |config|
 config.vm.box_url = "https://oracle.github.io/vagrant-projects/boxes/oraclelinux/8.json"
 config.vm.box = "oraclelinux/8"
  config.vm.provider "virtualbox" do |v|
  	v.memory = 1024
	end

end
